Repository moul/pipotron, pull requests merged in 2020-04, with the labels that each got.

#47 Update whatsapp-message-in-case-of-pandemic.yml
  dict/whatsapp-message-in-case-of-pandemic.yml
Labels: ✅ Approved

#48 Update whatsapp-message-in-case-of-pandemic.yml
  dict/whatsapp-message-in-case-of-pandemic.yml
Labels: ✅ Approved

#51 Create complot.yml
  dict/complot.yml
Labels: ✅ Approved

#53 quelques corrections et ajouts
  dict/compliment.yml
Labels: 🔍 Ready for Review

#54 Update compliment.yml
  dict/compliment.yml
Labels: ✅ Approved, 🔍 Ready for Review
